server:
  http_listen_port: 9080
  grpc_listen_port: 0
#  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: stardrop-logs

  docker_sd_configs:
    - host: unix:///var/run/docker.sock    
      refresh_interval: 5s
      filters:
        - name: name
          values: ["nginx", "frontend", "backend", "bot"]

  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container' 

    - source_labels: ['__meta_docker_container_id']
      regex: '(.+)'
      target_label: 'container_id' # Extracts container ID as a label